### ISSUE TITLE
The knowledgebase list shows only the first item after attempting to expand other items

### ISSUE THREAD

**Issue by ilatypov** [blabla1337/skf-flask#112]
What I did:
  After building skf-flask from github I saw the knowledgebase list showing a proper list of titles.  Clicking the first title showed the first item's contents.  I then clicked the second title.

What I expected:

  The second item's contents under the expanded second title.

What I observed instead:

  The first item expanded, showing the first item's contents.

**Comment by josh-gomez72** [comment]
Hey, I had a similar issue to but I managed to solve it.
You need to change the knowledge-base.html file so that instead of using 'counter' for id_items[counter] change it to id_items[(loop.index-1)] (this is in 4 spots)
Another thing to watch out for is if you have numbers in your file directory path to markdown/knowledge_base.
For example i had the directory name "C:\Program Files\Python27\Lib\site-packages...." so it was adding 27 onto all of the Ids.

**Comment by ilatypov** [comment]
Another change in the same pull did away with repetition inside the ASVS template and stopped using special counters.
