### ISSUE TITLE
Unable To Complete Checklist On Project

### ISSUE THREAD

**Issue by theHackPot** [blabla1337/skf-flask#113]
Hi, having issues completing a checklist..

Steps:
1. Run Checklist on existing project
2. Click "Start" to run Checklist
3. Page returned below - no option to select 'Yes','No' or 'N/A'

![image](https://cloud.githubusercontent.com/assets/17269499/22886514/260a40b4-f1f6-11e6-8638-aead1d2c3a74.png)

**Comment by adamnfish** [comment]
This (along with quite a few other problems) is fixed in [this PR](https://github.com/blabla1337/skf-flask/pull/111). Unfortunately, it looks like development on this repo has stalled. I've put a bit of work into creating a more stable version on [this fork](https://github.com/guardian/skf-flask), you may find it helps you out?

**Comment by theHackPot** [comment]
@adamnfish working as expected - thanks

**Comment by theHackPot** [comment]
@adamnfish Just noticed Java dropdown is missing from Code Language Selection 

![image](https://cloud.githubusercontent.com/assets/17269499/25488872/11a6308a-2b60-11e7-8605-d7dcc661ab88.png)

**Comment by adamnfish** [comment]
Great!

I'd guess the Java example link got taken out because there aren't many Java examples available at the moment:
https://github.com/blabla1337/skf-flask/tree/master/skf/markdown/code_examples/java

It'd be fantastic to flesh that out. There's a PR open that adds a lot of Java code examples. It'd be great to have a second set of eyes on that from someone with experience writing secure Java code, if you're so inclined.
https://github.com/blabla1337/skf-flask/pull/109

**Comment by theHackPot** [comment]
I added this line into header.html on your fork, seems to have worked

<li><a href="/code/java">Java</a></li>

[image: Inline image 1]

Unfortunately I'm not much of a coder but I'm interested in adding to the
project

**Comment by blabla1337** [comment]
issue solved, thanks guys
