### ISSUE TITLE
Add Android security checklist

### ISSUE THREAD

**Issue by seabaz** [blabla1337/skf-flask#117]
If possible i can help to add checklist for Android App development

**Comment by RiieCco** [comment]
Sounds awesome!

ASVS also had a chapter regarding mobile development but we did not added
it to skf because we lack full understanding of app development to witte
good knowledgebase items + code examples effectively.

So if you are willing to help us with that, it would be super awesome! 😄

Op zo 19 mrt. 2017 om 10:49 schreef seabaz <notifications@github.com>

**Comment by blabla1337** [comment]
We want to add the OWASP MASV to SKF, this is an awesome project and would cover this more in depth

**Comment by blabla1337** [comment]
Thanks to @martinmarsicano we now have it in SKF as the checklist. Will create a new issue for adding also KB items related to the mobile security controls.
