### ISSUE TITLE
Add PHP Code example: Sending emails in a secure fashion, e.g. how to use mail() securely

### ISSUE THREAD

**Issue by iambrosie** [blabla1337/skf-flask#354]
Hi all,

I  read the following two resources recently:
https://www.saotn.org/exploit-phps-mail-get-remote-code-execution/
https://www.ripstech.com/blog/2017/why-mail-is-dangerous-in-php/

Apparently the misuse is more frequent than one would like to (i.e. SwiftMailer,  Squirrelmail,  zend-mail, Phabricator, Roundcube were all vulnerable at one point) so I believe a PHP code example covering this might be useful.

**Comment by blabla1337** [comment]
Thank you for the feedback. I agree we could add this one to the PHP code examples. Will put it on the enhancement list.

**Comment by harshant** [comment]
Hi, i am willing to work on this issue.

**Comment by blabla1337** [comment]
That would be very nice 👍

**Comment by harshant** [comment]
Hi @blabla1337 , i have done the following commit https://github.com/harshant/skf-flask/commit/7154ec6ba8f44de53a9825d777a1620fcec6acb3 , i have not use [this](https://gist.github.com/Zenexer/40d02da5e07f151adeaeeaa11af9ab36) approach because it breaks RFC compliance.
If it's fine let me know i will submit a PR

**Comment by harshant** [comment]
Hi , i have also added header injection mitigation and now it should be good to go. Creating PR
