### ISSUE TITLE
non-admin user, 500 errors

### ISSUE THREAD

**Issue by blabla1337** [blabla1337/skf-flask#422]
Some API calls cannot be executed by a non-admin user and it should.

More background information:
https://skf.readme.io/v1.0/discuss/59fca4f4067f8d0028613d86

**Comment by martinmarsicano** [comment]
This problem comes with this line in skf/api/projects/business: groupmember = groupmembers.query.filter(groupmembers.userID == userID).one()

When a new user is created, there is no assignation to a group, so, this query ends empty, and some values that have to come from this line are needed in the project table.

Until we implement RBAC complete UI (with CRUD for groups, roles, etc) the best is to assign the new user to the only existing group. Will code that now.
