### ISSUE TITLE
Unclear description of JSON remote XSS

### ISSUE THREAD

**Issue by kciredor** [blabla1337/skf-flask#52]
Standard OWASP, XSS section, says:

"Are JSON response referencing resources in other domains?"

Which is unclear to me what is means. It is related to:

https://github.com/blabla1337/skf-flask/blob/master/skf/markdown/knowledge_base/94-knowledge_base--Input_rejection--.md

Which is more clear. So the label needs an update, or perhaps an INFO icon hover.

**Comment by RiieCco** [comment]
Hey Roderick!

I think you are absolutely right!

We were lately a little in two minds about keeping the owasp top 10 and
indeed update it with the info hovers or
removing it from skf since the top 10 is mistaken very often as good
security requirements.

Also as of yet the JSON items are linked to XSS but it really deserves a
knowledgebase item of its own since
there are alot of other mitigations needed when handling JSON properly. So
we expect that to be fixed in the next release of skf.

Thanx for your feedback, very much appreciated!










2015-06-29 14:40 GMT+02:00 Roderick Schaefer <notifications@github.com>:
