### ISSUE TITLE
Checklist review crash for any project

### ISSUE THREAD

**Issue by WebSabaki** [blabla1337/skf-flask#64]
Good morning.

When trying to check pre-development, everything is fine.
But when trying to check post-developement, I immedialtly reach 500 for any project I created or already existing.

```
File "/var/www/asvs/skf/skf.py", in project_checklists
  owasp_id = get_num(owasp_path[1])
 File "/var/www/asvs/skf/skf.py" ,  in get_num
   return int(''.join(ele for ele in x if ele.isdigit()))
ValueError: invalid literal for int() with base 10: ''
```

I tried to review why but I fail to really get the owasp_path concept so hard to then do better than submitting the issue :)

**Comment by RiieCco** [comment]
Hey!

Yes, we are very sorry for that.
We should mention that somewhere in the tutorials.

Whenever you get source directly from github instead of following the
normal installation tutorial
github tends to change some names in the file structures, breaking the
checklist functionality.

I shall post the fix for that issue to the skf.readme.io asap :) !





2015-10-12 8:29 GMT+02:00 Julien thomas <notifications@github.com>:

**Comment by adamnfish** [comment]
:+1:

Which files? I'm still getting this issue. It also doesn't put anything useful in the log files so it's quite hard to isolate the problem in production. Occurs on any request to `/project-checklists/*`.

Worth pointing out the Apache installation instructions tell users to clone the project directly out of GitHub so it'd be great to either fix the instructions (perhaps cloning a specific known-to-be-good commit / branch) or make sure master is always safe to deploy.

**Comment by adamnfish** [comment]
I've the same problem as the OP but for a different reason. Turns out if there's a hyphen in the path anywhere you get exceptions because of this line:

    owasp_id = get_num(owasp_path_lvl1[1])
    # this 1 is hard-coded ------------^

The hard coded `1` is there to ignore the hypen in the repo's name (`skf-flask`) and if there's another anywhere above it will fail. This really ought to be looking at the app's root path and ignoring anything outside of that (i.e. above). I'll try make a PR to fix this.

**Comment by blabla1337** [comment]
fixed in new release
